import { useCallback, useEffect, useRef, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:8002";
const WS_URL = import.meta.env.VITE_WS_URL ?? "ws://localhost:8002/ws/alerts";

const MAX_ALERTS = 200; // circular-buffer cap, mirrors ARCHITECTURE.md's "Circular buffer" data structure note
const INITIAL_BACKOFF_MS = 1000;
const MAX_BACKOFF_MS = 30000;
const EXPLANATION_POLL_INTERVAL_MS = 10000;

/**
 * Live alert feed for the dashboard. Replaces the Phase 2 polling hook
 * (useAlerts.js, now removed) with WebSocket push, per Phase 7a/7b.
 *
 * Three things happen here, all coordinated around one `alerts` array:
 *
 * 1. INITIAL FETCH — on mount, GET /api/v1/alerts once so the dashboard
 *    isn't empty while the WebSocket connection is still being established.
 *    This is the "don't lose the initial-fetch-then-supplement pattern"
 *    requirement — without it, a page load would only ever show alerts
 *    that arrived *after* the page opened.
 *
 * 2. LIVE PUSH — a WebSocket connection to /ws/alerts. Each message is one
 *    newly created alert (id, user_id, alert_type, severity, score,
 *    message, created_at — no explanation/mitigation_steps yet, see (3)).
 *    New alerts are prepended (most recent first) and the array is capped
 *    at MAX_ALERTS entries so a long-running session doesn't grow forever.
 *
 * 3. EXPLANATION BACKFILL — explanation/mitigation_steps are generated by a
 *    backend background task moments after the alert itself is created
 *    (Phase 6), and the Phase 7a WebSocket push does NOT re-fire once
 *    they're ready (that would need a second "alert updated" push type,
 *    which Phase 7a deliberately left as an open choice for this prompt —
 *    not built). There's also no per-alert GET endpoint to poll just one
 *    alert. So: while any visible alert is still missing an explanation,
 *    re-fetch the general alert list every 10s and merge explanation/
 *    mitigation_steps into matching ids already in view. This never
 *    reorders or drops WebSocket-delivered alerts, and does nothing at all
 *    once every visible alert has an explanation (or never will — see the
 *    known limitation below).
 *
 *    Known limitation: if Ollama is down for an extended period, this polls
 *    every 10s indefinitely for as long as an unexplained alert remains in
 *    the visible window, since there's no "give up after N attempts" cutoff.
 *    Acceptable for this phase's scope (a light-weight, bounded-by-buffer-
 *    size GET request) but worth knowing about.
 *
 * Reconnection: on an unexpected close, status flips to "disconnected" and
 * a reconnect is scheduled after an exponentially increasing delay (capped
 * at MAX_BACKOFF_MS), resetting back to the initial delay after any
 * successful reconnect.
 */
export function useAlertStream() {
  const [alerts, setAlerts] = useState([]);
  const [error, setError] = useState(null);
  const [connectionStatus, setConnectionStatus] = useState("connecting");

  const wsRef = useRef(null);
  const backoffRef = useRef(INITIAL_BACKOFF_MS);
  const reconnectTimeoutRef = useRef(null);
  const closedByUsRef = useRef(false);
  const hasConnectedBeforeRef = useRef(false);
  const alertsRef = useRef([]);

  // Keep a ref mirror of `alerts` so the explanation-polling interval below
  // can read the latest value without re-subscribing every time it changes.
  useEffect(() => {
    alertsRef.current = alerts;
  }, [alerts]);

  // --- 1. Initial fetch ---------------------------------------------------
  useEffect(() => {
    let active = true;

    async function fetchInitial() {
      try {
        const res = await fetch(`${API_URL}/api/v1/alerts?limit=${MAX_ALERTS}`);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        if (active) {
          setAlerts(data);
          setError(null);
        }
      } catch (err) {
        if (active) setError(err.message);
      }
    }

    fetchInitial();
    return () => {
      active = false;
    };
  }, []);

  // --- 2. Live WebSocket push, with reconnect-with-backoff ---------------
  const connect = useCallback(() => {
    closedByUsRef.current = false;
    setConnectionStatus(hasConnectedBeforeRef.current ? "reconnecting" : "connecting");

    const ws = new WebSocket(WS_URL);
    wsRef.current = ws;

    ws.onopen = () => {
      hasConnectedBeforeRef.current = true;
      backoffRef.current = INITIAL_BACKOFF_MS; // reset backoff after a clean connect
      setConnectionStatus("connected");
    };

    ws.onmessage = (event) => {
      try {
        const alert = JSON.parse(event.data);
        setAlerts((prev) => [alert, ...prev].slice(0, MAX_ALERTS));
      } catch {
        // Malformed push — drop it rather than crash the whole feed.
      }
    };

    ws.onclose = () => {
      wsRef.current = null;
      if (closedByUsRef.current) return; // unmounting — don't reconnect
      setConnectionStatus("disconnected");
      const delay = backoffRef.current;
      backoffRef.current = Math.min(backoffRef.current * 2, MAX_BACKOFF_MS);
      reconnectTimeoutRef.current = setTimeout(connect, delay);
    };

    ws.onerror = () => {
      // onclose fires right after onerror for a failed attempt; let onclose
      // own reconnect scheduling so we don't double-schedule a retry.
      ws.close();
    };
  }, []);

  useEffect(() => {
    connect();
    return () => {
      closedByUsRef.current = true;
      if (reconnectTimeoutRef.current) clearTimeout(reconnectTimeoutRef.current);
      wsRef.current?.close();
    };
  }, [connect]);

  // --- 3. Explanation backfill --------------------------------------------
  useEffect(() => {
    const id = setInterval(async () => {
      const current = alertsRef.current;
      const hasPending = current.some((a) => a.explanation == null);
      if (!hasPending) return;

      try {
        const res = await fetch(`${API_URL}/api/v1/alerts?limit=${MAX_ALERTS}`);
        if (!res.ok) return;
        const fresh = await res.json();
        const freshById = new Map(fresh.map((a) => [a.id, a]));

        setAlerts((prev) =>
          prev.map((a) => {
            const updated = freshById.get(a.id);
            return updated && updated.explanation != null && a.explanation == null ? updated : a;
          })
        );
      } catch {
        // Best-effort — a failed refresh just means we try again next tick.
      }
    }, EXPLANATION_POLL_INTERVAL_MS);

    return () => clearInterval(id);
  }, []);

  return { alerts, error, connectionStatus };
}
