"""add behavior profiles

Revision ID: ec624ab32c48
Revises: c9aa72bde662
Create Date: 2026-08-01 01:01:05.522475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec624ab32c48'
down_revision: Union[str, None] = 'c9aa72bde662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('known_ips', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('typical_login_hour', sa.Float(), nullable=True),
    sa.Column('login_hour_variance', sa.Float(), nullable=True),
    sa.Column('typical_days_between_logins', sa.Float(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_session_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('deviation_score', sa.Float(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_profiles_user_id'), 'behavior_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_profiles_user_id'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    # ### end Alembic commands ###
