events {}

http {
  log_format threatlens escape=json '{'
    '"request_id":"$request_id",'
    '"time_iso8601":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"host":"$host",'
    '"method":"$request_method",'
    '"request_uri":"$request_uri",'
    '"status":$status,'
    '"bytes_sent":$bytes_sent,'
    '"request_time":$request_time,'
    '"referrer":"$http_referer",'
    '"user_agent":"$http_user_agent",'
    '"threatlens_user":"$upstream_http_x_threatlens_user"'
  '}';

  access_log /var/log/nginx/threatlens.json.log threatlens;

  upstream demo_portal { server demo-site:8080; }

  server {
    listen 8080;
    server_name _;
    client_max_body_size 1m;

    location / {
      proxy_pass http://demo_portal;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_hide_header X-ThreatLens-User;
    }
  }
}
